# Generated by Django 3.2.8 on 2024-04-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='usuario',
            field=models.CharField(max_length=500),
        ),
    ]
